### PR TITLE
Company view/create flow and other fixes

### PR DESCRIPTION
**Pull request by zahrayh**

### CODE REVIEW

**Comment by rebaz36** [comment]
@zahrayh please make sure you comment out or remove consul logs before pushing, this is used for testing and shouldn't be included according to ESLint Rules

**Comment by rebaz36** [comment]
@zahrayh there's an issue with the /companyEdit.js file that's causing netlify fail to deploy, 
`1:41:21 AM: Error occurred prerendering page "/companyEdit". 
Read more: https://nextjs.org/docs/messages/prerender-error
1:41:21 AM: TypeError: Cannot read properties of undefined (reading 'charAt')
1:41:21 AM:     at Edit (/opt/build/repo/.next/server/pages/companyEdit.js:211:50)
1:41:21 AM:     at d (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
1:41:21 AM:     at bb (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
1:41:21 AM:     at a.b.render (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
1:41:21 AM:     at a.b.read (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
1:41:21 AM:     at Object.exports.renderToString (/opt/build/repo/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
1:41:21 AM:     at Object.renderPage (/opt/build/repo/node_modules/next/dist/server/render.js:596:45)
1:41:21 AM:     at Function.getInitialProps (/opt/build/repo/.next/server/pages/_document.js:601:19)
1:41:21 AM:     at Object.loadGetInitialProps (/opt/build/repo/node_modules/next/dist/shared/lib/utils.js:69:29)
1:41:21 AM:     at renderDocument (/opt/build/repo/node_modules/next/dist/server/render.js:609:48)
1:41:21 AM: info  - Generating static pages (9/13)
1:41:21 AM: info  - Generating static pages (13/13)
1:41:21 AM: > Build error occurred
1:41:21 AM: Error: Export encountered errors on following paths:
1:41:21 AM: 	/companyEdit
1:41:21 AM:     at /opt/build/repo/node_modules/next/dist/export/index.js:487:19
1:41:21 AM:     at runMicrotasks (<anonymous>)
1:41:21 AM:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
1:41:21 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
1:41:21 AM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:833:17
1:41:21 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
1:41:21 AM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:707:13
1:41:21 AM:     at async Span.traceAsyncFn (/opt/build/repo/node_modules/next/dist/telemetry/trace/trace.js:60:20)
1:41:21 AM:     at async Object.build [as default] (/opt/build/repo/node_modules/next/dist/build/index.js:77:25)
1:41:21 AM: error Command failed with exit code 1.
1:41:21 AM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

this is the netlify log I was not able to identify the issue 
@wisammechano we could use your help here

**Comment by zahrayh** [comment]
> @zahrayh there's an issue with the /companyEdit.js file that's causing netlify fail to deploy,
> 
> this is the netlify log I was not able to identify the issue @wisammechano we could use your help here
> 
> Image 11-1-21 at 02 16

**Comment by zahrayh** [comment]
@rebaz36  I think I know where the issue is now. I'll check it .

**Review by rebaz36 — APPROVED** [review]

**Pull request merged**
